name: VoiceServer
main: de.jakomi1.voiceServer.VoiceServer
version: 1.3.0
api-version: "1.8.8"
folia-supported: true

depend:
  - voicechat
permissions:
    voiceserver.vcgroup:
      description: Allows creating new voice chat groups.
      default: op
    voiceserver.vcserver:
      description: General VCServer Command.
      default: op
    voiceserver.vcpermission:
      description: Allows managing voice chat permissions.
      default: op

commands:
  vcgroup:
    description: Manage voice chat groups (list, create, add, kick, remove, info).
    usage: /vcgroup <list|create|add|kick|info|remove> [...]
    permission: voiceserver.vcgroup
  vcserver:
    description: Main plugin command (reload)
    usage: /vcserver <reload>
    permission: voiceserver.vcserver
  vcpermission:
    description: Manage voicechat permissions
    usage: /vcpermission <give/remove> <name> <permission>
    permission: voiceserver.vcpermission
  testcommand:
    usage: /test a
